# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
# Run locally with: goreleaser --rm-dist --snapshot --skip-publish
project_name: tbd
before:
  hooks:
    - go mod tidy
    - go mod download
builds:
- binary: '{{ .ProjectName }}'
  main: ./main.go
  env:
    - CGO_ENABLED=0
  ldflags:
    - -s -w -X main.commit={{.ShortCommit}}
    - -a -extldflags "-static"
  goos:
    - windows
    - linux
    - darwin
  goarch:
    - arm
    - arm64
    - amd64
  goarm:
    - 7
  ignore:
    - goos: darwin
      goarch: arm
    - goos: darwin
      goarch: arm64
    - goos: windows
      goarch: arm
    - goos: windows
      goarch: arm64
archives:
- replacements:
    darwin: macOS
    windows: win
    amd64: 64-bit
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .ProjectName }}_{{ .Tag }}"
nfpms:
  -
    package_name: tbd
    vendor: Luca Sepe
    homepage: https://lucasepe.it/
    maintainer: Luca Sepe <luca.sepe@gmail.com>
    description: A really simple way to create text templates with placeholders.
    license: MIT
    replacements:
      amd64: 64-bit
    formats:
      - deb
      - rpm
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
